version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Abcd1234#
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/configdb:/data/configdb

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: Abcd1234#
  #     ME_CONFIG_MONGODB_URL: mongodb://root:Abcd1234#@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
