version: '3'
services:
  mysql: # 名称
    image: mysql # mysql镜像版本
    container_name: mysql # 容器名称
    ports:
      - 3306:3306 # 指定宿主机端口与容器端口映射关系，宿主机:容器
    restart: always # 表示容器随docker启动自启
    environment:
      LANG: en_US.UTF-8 # 设置语言
      MYSQL_USER: xxg # 自定义创建的用户
      MYSQL_PASSWORD: Abcd1234 # 自定义创建的用户的密码
      MYSQL_DATABASE: auth # 自定义创建的库
      MYSQL_ROOT_PASSWORD: Abcd1234 # root用户密码
    volumes:
      - ./mysql/data:/var/lib/mysql # 映射数据目录
